name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - scala: 2
            project: rootJVM
          - scala: 2
            project: rootJS
          - scala: 2
            project: rootNative
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: "adopt@1.16"
    - uses: coursier/cache-action@v6
    - run: sbt -v
           checkGenTypeClasses
           $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi)
           "project ${{ matrix.project }}"
           test:compile
           $(if [[ "${ matrix.project }}" == "rootJS" ]]; then echo "test:fastOptJS"; fi)
    - run: sbt -v
           $(if [[ "${{ matrix.scala }}" == "3" ]]; then echo SetScala3; fi)
           "project ${{ matrix.project }}"
           test
           "project /"
           $(if [[ "${{ matrix.project }}" == "rootJVM" ]]; then echo "publishLocal"; echo "example/runAllMain"; fi)
    - run: rm -rf "$HOME/.ivy2/local" || true
